---
functional:
  - Пользователь должен иметь возможность выбрать тренировочный бой с ботом
  - Пользователь должен иметь возможность выбрать бой с реальным соперником
  - Пользователь должен иметь возможность выбрать язык программирования для выполнения задания
  - Пользователь должен иметь возможность общаться в чате с другими игроками
  - Пользователь должен иметь возможность просматирвать историю игр
  - Пользователь должен иметь возможность просматирвать статистику проведенных матчей
  - Пользователь должен иметь возможность просматривать рейтинг игроков
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Сайт должен быть доступен 24/7 (без неожиданных простоев)
  - Все ссылки на сайте должны вести на рабочие страницы (отсутствие битых ссылок)
  - Ошибки в интерфейсе должны быть понятными для пользователя
  - Формы должны проверять вводимые данные на корректность
  - Конфиденциальные данные пользователей не должны отображаться в URL
